<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<Copyright>Copyright © 1992-$([System.DateTime]::Now.ToString("yyyy")) Trimble Solutions Corporation and its licensors. All rights reserved.</Copyright>
		<OutputPath>bin\$(Configuration)\</OutputPath>
		<TargetFramework>net48</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<OutputPath>Installer/BuildDrop</OutputPath>
		<RootNamespace>WallRail2025</RootNamespace>
		<AssemblyName>WallRail2025</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
	  <Reference Include="Tekla.CustomUtilities">
	    <HintPath>..\..\Apps\2025\Tekla.CustomUtilities\bin\Debug\Tekla.CustomUtilities.dll</HintPath>
	  </Reference>
	  <Reference Include="Tekla.Structures">
	    <HintPath>C:\Program Files\Tekla Structures\2025.0\bin\Tekla.Structures.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Tekla.Structures.Datatype">
	    <HintPath>C:\Program Files\Tekla Structures\2025.0\bin\Tekla.Structures.Datatype.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Tekla.Structures.Dialog">
	    <HintPath>C:\Program Files\Tekla Structures\2025.0\bin\Tekla.Structures.Dialog.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Tekla.Structures.Model">
	    <HintPath>C:\Program Files\Tekla Structures\2025.0\bin\Tekla.Structures.Model.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	  <Reference Include="Tekla.Structures.Plugins">
	    <HintPath>C:\Program Files\Tekla Structures\2025.0\bin\Tekla.Structures.Plugins.dll</HintPath>
	    <Private>False</Private>
	  </Reference>
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="Properties\Resources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="set envDir=2026.0\Environments\common\extensions\WallRail2025&#xA;set tsDirA=C:\ProgramData\Trimble\Tekla Structures\&#xA;&#xA;if $(ConfigurationName) == Debug (&#xA;    :: Check if the target directory exists and create it if not&#xA;    IF NOT EXIST &quot;%25tsDirA%25%25envDir%25&quot; MKDIR &quot;%25tsDirA%25%25envDir%25&quot;&#xA;    &#xA;    :: Now perform the copy if the base directory exists (which it should if the above succeeded or it already existed)&#xA;    if exist &quot;%25tsDirA%25&quot; xcopy &quot;$(TargetDir)*$(TargetExt)&quot; &quot;%25tsDirA%25\%25envDir%25&quot; /y /c /q&#xA;)&#xD;&#xA;)" />
	</Target>
</Project>